apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: phishguard-secrets
spec:
  refreshInterval: 300s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore

  target:
    name: phishguard-runtime-secrets

  data:
    - secretKey: jwt_secret
      remoteRef:
        key: secret/data/phishguard/jwt
        property: jwt_secret

    - secretKey: virustotal_api
      remoteRef:
        key: secret/data/phishguard/virustotal
        property: api_key
