apiVersion: apps/v1
kind: Deployment
metadata:
  name: phishguard-worker
  labels:
    app: phishguard-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: phishguard-worker
  template:
    metadata:
      labels:
        app: phishguard-worker
    spec:
      containers:
      - name: worker
        image: cyberzenithai/phishguard-worker:0.9.0
        env:
        - name: REDIS_URL
          value: "redis://redis-service:6379/0"
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: phishguard-secrets
              key: secret-key
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
